version: '3.5'

services:
  telegram_bot:
    build: .
    depends_on:
      - db_auth
  db_auth:
    container_name: db_auth
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    image: postgres:16.0-alpine